### PR TITLE
Migrate to macos-13 runner image

### PR DESCRIPTION
**Pull request by jdblischak**
macos-12 runner image is deprecated

xref: https://github.com/actions/runner-images/issues/10721, https://github.com/TileDB-Inc/TileDB/pull/5350

### CODE REVIEW

**Comment by teo-tsirpanis** [comment]
Apparently we use a too old Gradle version.

**Comment by jdblischak** [comment]
Rebased onto main to incorporate #786, which removed the spark jobs

**Comment by gspowley** [comment]
It looks like `javadoc` "linting" is failing on macos. Is there a way to disable that?

**Comment by teo-tsirpanis** [comment]
The error seems to be:

```
Execution failed for task ':sourceJar'.
> Entry io/tiledb/libvcfnative/VCFBedFile.java is a duplicate but no duplicate handling strategy has been set. Please refer to https://docs.gradle.org/8.10.2/dsl/org.gradle.api.tasks.Copy.html#org.gradle.api.tasks.Copy:duplicatesStrategy for details.
```

**Comment by gspowley** [comment]
Good point, when running locally on Linux I didn't get that error message.

This change allowed the build to complete on my local system.
```diff
diff --git a/apis/java/build.gradle b/apis/java/build.gradle
index 78c9fada..1a98c55b 100644
--- a/apis/java/build.gradle
+++ b/apis/java/build.gradle
@@ -213,6 +213,7 @@ task sourceJar(type: Jar) {
 task javadocJar(type: Jar, dependsOn: javadoc) {
     classifier "javadoc"
     from javadoc.destinationDir
+    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
 }
 
 artifacts {
```

**Comment by jdblischak** [comment]
@teo-tsirpanis @gspowley thanks for the troubleshooting assistance!

@dudoslav opened a new PR #793 to combine everything, and the CI is green. Thanks Dušan!

**Pull request closed without merging**
