### PR TITLE
Upgrade Embedded to 2.24.1

### PR DESCRIPTION
**Pull request by awenocur**

### CODE REVIEW

**Review by jdblischak — APPROVED** [review]

**Comment by jdblischak** [comment]
There are updates in this PR in addition to bumping libtiledb to 2.24.1 and pinning numpy<2. Are these updates to the source files and test files related to libtiledb 2.24.1? If not, could you please briefly document them here in this PR?

**Comment by awenocur** [comment]
The additional commits are from #731. That PR includes the NumPy pin, and ideally should be part of the same release as the Core version bump, so this is ahead of it.

**Review by johnkerl — APPROVED** [review]

**Review by gspowley — CHANGES_REQUESTED** [review]
Please remove the gVCF AF related changes.

**Comment by jdblischak** [comment]
Please rebase onto main to obtain the latest CI fixes

**Review by gspowley — APPROVED** [review]

**Pull request merged**
