### PR TITLE
update htslib to 1.20

### PR DESCRIPTION
**Pull request by awenocur**

### CODE REVIEW

**Review by gspowley — APPROVED** [review]

**Review by teo-tsirpanis — CHANGES_REQUESTED** [review]
The Windows feedstock is not yet updated.

**Comment by ihnorton** [comment]
Is this ready to go after https://github.com/TileDB-Inc/m2w64-htslib-build/commit/562caac9ca4d29250d032bd2b10b37ad5abaf168 ?

**Comment by teo-tsirpanis** [comment]
After these lines are updated yes. https://github.com/TileDB-Inc/TileDB-VCF/blob/8cd46f4cd06d2cbc0f6c6461f2abe4126a1f12b2/libtiledbvcf/cmake/Modules/FindHTSlib.cmake#L97-L98

**Review by teo-tsirpanis — APPROVED** [review]
Thanks!

**Pull request merged**
