### PR TITLE
Illegal instruction fix

### PR DESCRIPTION
**Pull request by dudoslav**
https://github.com/TileDB-Inc/tiledb-vcf-feedstock/pull/126

### CODE REVIEW

**Comment by dudoslav** [comment]
I am not sure how big of an issue is this:
```
[100%] Linking CXX executable tiledb_vcf_unit
ld: warning: object file (CMakeFiles/tiledb_vcf_unit.dir/src/unit-bitmap.cc.o) was built for newer macOS version (12.0) than being linked (11.0)
ld: warning: object file (CMakeFiles/tiledb_vcf_unit.dir/src/unit-c-api-reader.cc.o) was built for newer macOS version (12.0) than being linked (11.0)
ld: warning: object file (CMakeFiles/tiledb_vcf_unit.dir/src/unit-c-api-writer.cc.o) was built for newer macOS version (12.0) than being linked (11.0)
ld: warning: object file (CMakeFiles/tiledb_vcf_unit.dir/src/unit-vcf-export.cc.o) was built for newer macOS version (12.0) than being linked (11.0)
ld: warning: object file (CMakeFiles/tiledb_vcf_unit.dir/src/unit-vcf-delete.cc.o) was built for newer macOS version (12.0) than being linked (11.0)
ld: warning: object file (CMakeFiles/tiledb_vcf_unit.dir/src/unit-vcf-iter.cc.o) was built for newer macOS version (12.0) than being linked (11.0)
ld: warning: object file (CMakeFiles/tiledb_vcf_unit.dir/src/unit-vcf-store.cc.o) was built for newer macOS version (12.0) than being linked (11.0)
ld: warning: object file (CMakeFiles/tiledb_vcf_unit.dir/src/unit-vcf-utils.cc.o) was built for newer macOS version (12.0) than being linked (11.0)
ld: warning: object file (CMakeFiles/tiledb_vcf_unit.dir/src/unit-vcf-time-travel.cc.o) was built for newer macOS version (12.0) than being linked (11.0)
ld: warning: object file (CMakeFiles/tiledb_vcf_unit.dir/src/unit.cc.o) was built for newer macOS version (12.0) than being linked (11.0)
```

**Review by awenocur — APPROVED** [review]

**Comment by ihnorton** [comment]
IMO should pass this through the c flags in the conda feedstock rather than hardcoding here

**Comment by dudoslav** [comment]
This change does not help in feedstocks anyway:

https://github.com/TileDB-Inc/tiledb-vcf-feedstock/pull/126
https://github.com/TileDB-Inc/tiledb-vcf-feedstock/pull/127

**Comment by teo-tsirpanis** [comment]
> IMO should pass this through the c flags in the conda feedstock rather than hardcoding here

Agree, even better we should pass [`-DCMAKE_OSX_DEPLOYMENT_TARGET=12.0`](https://cmake.org/cmake/help/latest/variable/CMAKE_OSX_DEPLOYMENT_TARGET.html).

**Comment by dudoslav** [comment]
The second PR that I linked uses env variable to set MACOS target:
https://github.com/TileDB-Inc/tiledb-vcf-feedstock/pull/127/files

**Comment by ihnorton** [comment]
Could you please try _this branch_ in one of the PRs above so we can check whether it fixes the issue (maybe we are overriding the deployment target variable somewhere).

**Comment by dudoslav** [comment]
> Could you please try _this branch_ in one of the PRs above so we can check whether it fixes the issue (maybe we are overriding the deployment target variable somewhere).

I already did that, didn't I?: https://github.com/TileDB-Inc/tiledb-vcf-feedstock/pull/126/files#diff-f3725a55bf339595bf865fec73bda8ac99f283b0810c205442021f29c06eea9aR12

I referenced this commit in tiledb-vcf-feedstock

**Comment by ihnorton** [comment]
Sorry, missed that - ok, I see, it didn't fix the issue.

**Comment by dudoslav** [comment]
This PR is not needed in order to fix tiledb-vcf-feedstock so I am closing it

**Pull request closed without merging**
